version: 2
registries:
  composer-packages-dekodes-no:
    type: composer-repository
    url: https://packages.dekodes.no
    username: ${{secrets.COMPOSER_REPOSITORY_PACKAGES_DEKODES_NO_USERNAME}}
    password: ${{secrets.COMPOSER_REPOSITORY_PACKAGES_DEKODES_NO_PASSWORD}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Oslo
      time: "09:00"
    open-pull-requests-limit: 30
    rebase-strategy: disabled
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Oslo
      time: "09:00"
    open-pull-requests-limit: 30
    rebase-strategy: disabled
    registries:
      - composer-packages-dekodes-no
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Oslo
      time: "09:00"
